a = input('\033[7;31;40mDigite algo')
print('\033[7;31;40mO tipo primitivo desse valor é',type(a))
print('\033[7;31;40Só tem espaço?',a.isspace())
print('É um numero?',a.isnumeric())
print('É alfabetico?',a.isalpha())
print('è Alfanumerico?' ,a.isnumeric())
print('Está em maiuscula?' ,a.isupper())
print('Está em minuscula?' ,a.islower())
print('Esta capitalizada?',a.istitle())