#nome = input('Digite seu nome:')
#caracteres = len(nome.strip())
#print('Analisando seu nome {} em maiusculas e minusculas'.format(nome))
#print(nome.upper())
#print(nome.lower())
#print('Analizando a quantidade de caracteres o nome {} possui {} caracteres'.format(nome,caracteres))

nome = str(input('Digite seu nome completo')).strip()
print(nome.lower())
print(nome.upper())
print('Seu nome em maiusculas {}'.format(nome.upper()))
print('Seu nome em minusculas é {}'.format(nome.lower()))
print('Seu nome tem ao todo {} caracteres'.format(len(nome) -nome.count(' ')))
nome.count('')
separa = nome.split()
print('seu primeiro nome é {} e ele tem {}'.format(separa[0],len(separa[0])))
